### ISSUE TITLE
Only see a single line

### ISSUE THREAD

**Issue by ghost** [GameMakerDevsSlack/WAD-Loader#1]
I'm curious how this works, I tested it out and i can only see a single white diagonal line across the screen. Is this supposed to render a map as an example? I noticed that it also draw the names of the contents and map data read from the WAD file.

**Comment by Sidorakh** [comment]
It's very much unfinished. It seemed to kind of work when I tested it with Doom, though my memory might not be the best about this. I'm thinking of working on this again soon, but that's probably a long way off (when I actually have time).
